"""zda

Revision ID: 0efd4873ca1c
Revises: d61d6f59dcff
Create Date: 2024-08-10 21:15:45.100166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efd4873ca1c'
down_revision = 'd61d6f59dcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
