"""d

Revision ID: 4882a7ce1f3c
Revises: 
Create Date: 2024-07-27 13:15:11.447439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4882a7ce1f3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('industry', sa.String(length=20), nullable=True),
    sa.Column('budgets', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('niche', sa.String(length=20), nullable=True),
    sa.Column('reach', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], name='fk_campaign_sponsor_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_start_date'), ['start_date'], unique=False)

    op.create_table('ad_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='fk_adrequest_campaign_id'),
    sa.ForeignKeyConstraint(['influencer_id'], ['user.id'], name='fk_adrequest_influencer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_request')
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_start_date'))
        batch_op.drop_index(batch_op.f('ix_campaign_end_date'))

    op.drop_table('campaign')
    op.drop_table('user')
    # ### end Alembic commands ###
