"""xc

Revision ID: 700f87e86c3e
Revises: e1ef79e5e7fc
Create Date: 2024-08-03 22:50:42.197061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700f87e86c3e'
down_revision = 'e1ef79e5e7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
