"""jhkg

Revision ID: 81d75fe179fe
Revises: fdc81b13e63c
Create Date: 2024-08-07 22:52:27.064605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d75fe179fe'
down_revision = 'fdc81b13e63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_adrequest_sponsor_id', 'user', ['sponsor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_adrequest_sponsor_id', type_='foreignkey')
        batch_op.drop_column('sponsor_id')

    # ### end Alembic commands ###
