"""z

Revision ID: b20aed828c29
Revises: a232e0ae1b44
Create Date: 2024-07-27 17:42:42.563765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20aed828c29'
down_revision = 'a232e0ae1b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('influencer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_campaign_influencer_id', 'user', ['influencer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaign_influencer_id', type_='foreignkey')
        batch_op.drop_column('influencer_id')

    # ### end Alembic commands ###
