"""zdj

Revision ID: d61d6f59dcff
Revises: c3813288b061
Create Date: 2024-08-10 21:11:21.468915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61d6f59dcff'
down_revision = 'c3813288b061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
