"""d

Revision ID: e1ef79e5e7fc
Revises: fecf778cc87c
Create Date: 2024-08-03 21:02:16.531608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ef79e5e7fc'
down_revision = 'fecf778cc87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blocked')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
