"""opk

Revision ID: fdc81b13e63c
Revises: 700f87e86c3e
Create Date: 2024-08-04 07:13:09.180186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc81b13e63c'
down_revision = '700f87e86c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('flagged',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('blocked',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('blocked',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('flagged',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
