"""l

Revision ID: fecf778cc87c
Revises: b20aed828c29
Create Date: 2024-07-28 06:37:52.246961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecf778cc87c'
down_revision = 'b20aed828c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negotiated_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('negotiation_status', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_column('negotiation_status')
        batch_op.drop_column('negotiated_amount')

    # ### end Alembic commands ###
